apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "k8s.name" . }}
    helm.sh/chart: {{ include "k8s.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.nginx.port }}
